M48
; DRILL file {KiCad 7.0.8} date Fri Nov 17 11:36:38 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-17T11:36:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.5665Y-2.0158
X2.5665Y-3.8642
X3.5315Y-2.0158
X3.5315Y-3.8642
T0
M30
