#Proceso para que el elemento identifique el color correcto e incorrecto:
    if O==True:
        if verde==True:
            print("Correcto")
            d.home()
            d.clear()
            d.write('¡Correcto!')
            ledg.on()
            celebrate(d, my_servo, 3)  # Celebrar durante 2 segundos
            time.sleep(1)
            ledr.off()
            ledg.off()
            ledb.off()
            ledi.off()
            assign_random_number()
            
        elif azul==True or rojo==True:
            print("Incorrecto")
            d.home()
            d.clear()
            d.write('Incorrecto :(')
            d.color(255, 255, 0)
            ledi.on()
            time.sleep(3)
            ledr.off()
            ledg.off()
            ledb.off()
            ledi.off()
            assign_random_number()
    if M==True:
        if rojo==True:
            print("Correcto")
            d.home()
            d.clear()
            d.write('¡Correcto!')
            ledr.on()
            celebrate(d, my_servo, 3)  # Celebrar durante 2 segundos
            time.sleep(1)
            ledr.off()
            ledg.off()
            ledb.off()
            ledi.off()
            assign_random_number()
        elif azul==True or verde==True:
            print("Incorrecto")
            d.home()
            d.clear()
            d.write('Incorrecto :(')
            d.color(255, 255, 0)
            ledi.on()
            time.sleep(3)
            ledr.off()
            ledg.off()
            ledb.off()
            ledi.off()
            assign_random_number()
    if P==True:
        if azul==True:
            print("Correcto")
            d.home()
            d.clear()
            d.write('¡Correcto!')
            ledb.on()
            celebrate(d, my_servo, 3)  # Celebrar durante 2 segundos
            time.sleep(3)
            ledr.off()
            ledg.off()
            ledb.off()
            ledi.off()
            assign_random_number()
        elif rojo==True or verde==True:
            print("Incorrecto")
            d.home()
            d.clear()
            d.write('Incorrecto :(')
            d.color(255, 255, 0)
            ledi.on()
            time.sleep(3)
            ledr.off()
            ledg.off()
            ledb.off()
            ledi.off()
            assign_random_number()
    time.sleep(1)
